name: CI

on: [push, pull_request]

jobs:
  my-composite-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run my composite action
        uses: ./.github/actions/my-composite-action
        with:
          my-input: 'some input value'
