name: CI

on: [push, pull_request]

jobs:
  my-composite-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run my composite action
        uses: ./.github/actions/my-composite-action
        # with:
        #   my-input: 'some input value'
        env:
          GH_NAME: ${{ secrets.GH_NAME }}
          GH_ADMIN_TOKEN: ${{ secrets.REPORTS_PAT }}

      - name: Github Copilot report
        uses: actions/upload-artifact@v2
        with:
          name: Copilot_Users${{ steps.date.outputs.date }}
          path: |
           ${{ github.workspace }}/*.csv
           ${{ github.workspace }}/*.log
